name: LegendTeleportEssentials
main: essentialsTP\essentialsTP
version: 1.0.0
api: [3.0.0]
extensions: [sqlite3]
commands:
 home:
  description: Teleports you home /home will list homes /home <homename> will teleport you.
  usage: "/home or /home <homename>"
  permission: legendteleportessentials.command.home
 sethome:
  description: Sets your home, use names for multiple homes.
  usage: "/sethome <homename>"
  permission: legendteleportessentials.command.sethome
 delhome:
  description: Delete your selected home.
  usage: "/delhome <homename>"
  permission: legendteleportessentials.command.delhome
 back:
  description: Teleports you to your last known death location.
  usage: "/back"
  permission: legendteleportessentials.command.back
 wild:
  description: Teleport to a random location in the world.
  usage: "/wild"
  permission: legendteleportessentials.command.wild
 setspawn:
  description: Sets world spawn point.
  usage: "/setspawn"
  permission: legendteleportessentials.command.setspawn
 spawn:
  description: Teleports to world spawn point.
  usage: "/spawn"
  permission: legendteleportessentials.command.spawn
 avwarp:
  description: Warps you to a location /avwarp will list avwarps /avwarp <avwarpname> will teleport you.
  usage: "/avwarp or /avwarp <avwarpname>"
  permission: legendteleportessentials.command.tpahere
 setavwarp:
  description: Sets a avwarp location.
  usage: "/setavwarp <avwarpname>"
  permission: legendteleportessentials.command.setavwarp
 delavwarp:
  description: Delete a avwarp location.
  usage: "/delavwarp <avwarpname>"
  permission: legendteleportessentials.command.delavwarp
 tpa:
  description: Send teleport request to player to teleport you to player.
  usage: "/tpa <player>"
  permission: legendteleportessentials.command.tpa
 tpahere:
  description: Send teleport request to teleport player to you.
  usage: "/tpahere <player>"
  permission: legendteleportessentials.command.tpahere
 tpaccept:
  description: Accept a teleport request.
  usage: "/tpaccept"
  permission: legendteleportessentials.command.tpaccept
 tpdeny:
   description: decline all active teleport requests.
   usage: "/tpdeny"
   permission: legendteleportessentials.command.tpdeny
permissions:
 legendteleportessentials.*:
  default: op
  description: "Allows all essentialsTP commands"
  children:
   legendteleportessentials.command.*:
    description: "Allows player to use commands"
    default: op
    children:
     legendteleportessentials.command.tpdeny:
      description: "Allows player to decline request"
      default: true
     legendteleportessentials.command.tpaccept:
      description: "Allows player to accept request"
      default: true
     legendteleportessentials.command.tpahere:
      description: "Allows player to teleport player to them"
      default: true
     legendteleportessentials.command.tpa:
      description: "Allows player to teleport to another player"
      default: true
     legendteleportessentials.command.delavwarp:
      description: "Allows player to delete avwarps"
      default: op
     legendteleportessentials.command.setavwarp:
      description: "Allows player to set avwarps"
      default: op
     legendteleportessentials.command.avwarp:
      description: "Allows player use avwarps"
      default: true
     legendteleportessentials.command.setspawn:
      description: "Allows player to set spawn for world"
      default: op
     legendteleportessentials.command.spawn:
      description: "Allows player use spawn command"
      default: true
     legendteleportessentials.command.wild:
      description: "Allows player to teleport to a random location in world"
      default: true
     legendteleportessentials.command.back:
      description: "Allows player go back to their last death location"
      default: true
     legendteleportessentials.command.delhome:
      description: "Allows player to delete their homes"
      default: true
     legendteleportessentials.command.sethome:
      description: "Allows player to set their homes"
      default: true
     legendteleportessentials.command.home:
      description: "Allows player to use the home command"
      default: true
     legendteleportessentials.command.bedsethome:
      description: "Allows player to set home with their bed"
      default: true
     legendteleportessentials.command.sign.avwarp:
      description: "Allows player to use avwarp signs"
      default: true
     legendteleportessentials.command.sign.wild:
      description: "Allows player to use wild signs"
      default: op
     legendteleportessentials.command.sign.spawn:
      description: "Allows player to use spawn signs"
      default: true
     legendteleportessentials.command.sign.avwarp.create:
      description: "Allows player to create avwarp signs"
      default: op
     legendteleportessentials.command.sign.wild.create:
      description: "Allows player to create wild signs"
      default: op
     legendteleportessentials.command.sign.spawn.create:
      description: "Allows player to create spawn signs"
      default: op
     legendteleportessentials.command.sign.avwarp.break:
      description: "Allows player to break avwarp signs"
      default: op
     legendteleportessentials.command.sign.wild.break:
      description: "Allows player to break wild signs"
      default: op
     legendteleportessentials.command.sign.spawn.break:
      description: "Allows player to break spawn signs"
      default: op
