---
plugin-name: LegendTeleportEssentials
sqlite-dbname: essentials_tp
tpa-here-cooldown: "0"
tp-home-cooldown: "0"
tp-warp-cooldown: "0"
tp-spawn-cooldown: "0"
MOTD: Welcome to this awsome plugin showcase was hell for the first day but hey lol
wild-MaxX: "1000"
wild-MaxY: "1000"
bed-sets-home: "true"
Lang_invalid_usage: 'INVALID USAGE:'
Lang_command_only_use_ingame: This command can only be used in the game.
Lang_no_permissions: '§cUnknown command. Try /help for a list of commands'
Lang_teleport_home: 
Lang_teleport_spawn: 
Lang_teleport_wild: 
Lang_teleport_death: 
Lang_no_spawn_set: 
Lang_teleport_spawn_original: 
Lang_spawn_set: 
Lang_your_homes: 'Your Homes:'
Lang_no_home_set: 
Lang_no_home_name: 
Lang_home_set: Home set as
Lang_home_delete_1: 'Home named:'
Lang_home_delete_2: has been deleted.
Lang_no_teleport_self: 
Lang_player_not_online: Player is not online.
Lang_sent_request_you: sent a request to teleport to you.
Lang_sent_request_them: sent a request to you, to teleport to them.
Lang_accept_request: to accept this request.
Lang_decline_request: to decline this request.
Lang_request_expire_1: This request is only good for
Lang_request_expire_2: Seconds
Lang_request_expire_3: before it expires.
Lang_type: Type
Lang_no_active_request: No active request exist.
Lang_warps: 'Warps:'
Lang_no_warps: This server has no warps.
Lang_no_warp_listed: There is no warp by that name listed.
Lang_warp_set: Warp set as
Lang_warp_to: §bYou warped to §9
Lang_warp_delete_1: 'Warp named:'
Lang_warp_delete_2: has been deleted.
Lang_no_warps_name: No Warps matching that name for this server.
Land_chunk_not_loaded: 
Lang_action_cooldown: 
Lang_no_death: 
...
